"use client";

import { useEffect, useMemo, useState } from "react";
import { CalendarDays, ClipboardList, RefreshCw } from "lucide-react";
import { AdminHeader, AdminSidebar, AdminSidebarBackdrop } from "../admin-chrome";

type Booking = { id: string; created_at: string; farmer_name: string; owner_name: string; listing_title: string; rental_start: string | null; rental_end: string | null; duration_days: number; total_amount: number; rental_status: string; payment_status: string; payment: { platform_commission?: number; owner_amount?: number; payout_status?: string } | null };
const money = (value: unknown) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(Number(value ?? 0));
const pretty = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (character) => character.toUpperCase());

function Status({ value }: { value: string }) { return <span className={`admin-status admin-status-${value === "completed" || value === "paid" ? "success" : value === "cancelled" || value === "failed" ? "danger" : value === "in_progress" ? "blue" : "warning"}`}><i />{pretty(value)}</span>; }

export default function AdminBookings({ adminName }: { adminName: string }) {
  const [bookings, setBookings] = useState<Booking[]>([]); const [filter, setFilter] = useState("all"); const [error, setError] = useState(""); const [open, setOpen] = useState(false);
  async function load() { const response = await fetch("/api/admin/bookings", { cache: "no-store" }); const body = (await response.json().catch(() => ({}))) as { bookings?: Booking[]; message?: string }; if (!response.ok) throw new Error(body.message ?? "Unable to load bookings"); setBookings(body.bookings ?? []); }
  useEffect(() => { const timer = window.setTimeout(() => { void load().catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Unable to load bookings")); }, 0); return () => window.clearTimeout(timer); }, []);
  const visible = useMemo(() => filter === "all" ? bookings : bookings.filter((booking) => booking.rental_status === filter), [bookings, filter]);
  return <div className="admin-dashboard admin-subpage"><AdminSidebarBackdrop open={open} onClose={() => setOpen(false)} /><AdminSidebar active="bookings" open={open} onClose={() => setOpen(false)} /><main className="admin-main"><AdminHeader title="Bookings" subtitle="Monitor every rental from payment confirmation through completion." adminName={adminName} onMenu={() => setOpen(true)} /><section className="admin-panel admin-subpage-panel"><div className="admin-panel-heading"><div><p className="admin-eyebrow">Rental lifecycle</p><h2><ClipboardList size={20} />All bookings</h2></div><button className="admin-refresh-button" type="button" onClick={() => void load()}><RefreshCw size={15} /> Refresh</button></div><div className="admin-filter-row">{["all", "confirmed", "in_progress", "completed", "cancelled"].map((item) => <button type="button" key={item} className={filter === item ? "is-active" : undefined} onClick={() => setFilter(item)}>{item === "all" ? "All" : pretty(item)}</button>)}</div>{error ? <div className="admin-error" role="alert">{error}</div> : visible.length ? <div className="admin-table-scroll"><table className="admin-table admin-bookings-table"><thead><tr>{["Booking", "Farmer", "Owner", "Equipment", "Dates", "Payment", "Rental status", "Farmer total", "Commission", "Owner amount", "Payout"].map((heading) => <th key={heading}>{heading}</th>)}</tr></thead><tbody>{visible.map((booking) => <tr key={booking.id}><td><strong>MR-{booking.id.slice(0, 8).toUpperCase()}</strong><small>{new Date(booking.created_at).toLocaleDateString("en-IN")}</small></td><td>{booking.farmer_name}</td><td>{booking.owner_name}</td><td>{booking.listing_title}</td><td className="nowrap"><CalendarDays size={13} />{booking.rental_start ?? "Purchase"}{booking.rental_end ? ` → ${booking.rental_end}` : ""}<small>{booking.duration_days} day(s)</small></td><td><Status value={booking.payment_status} /></td><td><Status value={booking.rental_status} /></td><td className="nowrap">{money(booking.total_amount)}</td><td className="nowrap">{money(booking.payment?.platform_commission)}</td><td className="nowrap">{money(booking.payment?.owner_amount)}</td><td><Status value={booking.payment?.payout_status ?? "pending"} /></td></tr>)}</tbody></table></div> : <div className="admin-empty"><ClipboardList size={20} />No bookings match this filter.</div>}</section></main></div>;
}
