export type ProductLanguage = "te" | "en";

export type MarketplaceListing = {
  id: number;
  title: string;
  category: "tractor" | "rotavator" | "harvester";
  image: string;
  imageAlt: Record<ProductLanguage, string>;
  price: number;
  unit: Record<ProductLanguage, string>;
  district: string;
  mandal: string;
  village: string;
  owner: string;
  phone: string;
  verified: boolean;
  available: boolean;
  year: number;
  specification: string;
  responseTime: Record<ProductLanguage, string>;
  description: Record<ProductLanguage, string>;
};

export const marketplaceCategories = [
  { id: "tractor", en: "Tractor", te: "ట్రాక్టర్" },
  { id: "rotavator", en: "Rotavator", te: "రోటావేటర్" },
  { id: "harvester", en: "Harvester", te: "హార్వెస్టర్" },
] as const;

export const marketplaceListings: MarketplaceListing[] = [
  {
    id: 1,
    title: "Mahindra 575 DI Tractor",
    category: "tractor",
    image: "/equipment/tractor-red.png",
    imageAlt: {
      te: "వరి పొలం దగ్గర ఎరుపు రంగు ట్రాక్టర్",
      en: "Red tractor beside a paddy field",
    },
    price: 1500,
    unit: { te: "రోజు", en: "day" },
    district: "Krishna",
    mandal: "Kanchikacherla",
    village: "Moguluru",
    owner: "రమేష్ గారు",
    phone: "9876543210",
    verified: true,
    available: true,
    year: 2016,
    specification: "45 HP • Driver available",
    responseTime: { te: "సాధారణంగా 12 నిమిషాల్లో స్పందిస్తారు", en: "Usually replies in 12 minutes" },
    description: {
      te: "దున్నడం, విత్తనాల ముందు భూమి సిద్ధం చేయడం మరియు రవాణా పనులకు బాగా నిర్వహించిన ట్రాక్టర్.",
      en: "A well-maintained tractor for ploughing, field preparation, and local haulage.",
    },
  },
  {
    id: 2,
    title: "Sonalika Rotavator 7 Feet",
    category: "rotavator",
    image: "/equipment/rotavator-orange.png",
    imageAlt: {
      te: "పొలం దగ్గర నారింజ రంగు రోటావేటర్",
      en: "Orange rotavator beside a prepared field",
    },
    price: 1000,
    unit: { te: "ఎకరం", en: "acre" },
    district: "Krishna",
    mandal: "Kanchikacherla",
    village: "Srirampuram",
    owner: "లక్ష్మి అగ్రో సర్వీస్",
    phone: "9848011122",
    verified: true,
    available: true,
    year: 2021,
    specification: "7 ft • Operator optional",
    responseTime: { te: "సాధారణంగా 20 నిమిషాల్లో స్పందిస్తారు", en: "Usually replies in 20 minutes" },
    description: {
      te: "విత్తనాల ముందు నేలను త్వరగా మరియు సమంగా సిద్ధం చేయడానికి 7 అడుగుల రోటావేటర్.",
      en: "A seven-foot rotavator for fast and even soil preparation before sowing.",
    },
  },
  {
    id: 3,
    title: "Vishal 435 Paddy Harvester",
    category: "harvester",
    image: "/equipment/harvester-green.png",
    imageAlt: {
      te: "వరి పొలంలో ఆకుపచ్చ హార్వెస్టర్",
      en: "Green harvester in a mature paddy field",
    },
    price: 7500,
    unit: { te: "ఎకరం", en: "acre" },
    district: "West Godavari",
    mandal: "Bhimavaram",
    village: "Narasimhapuram",
    owner: "కృష్ణ హార్వెస్ట్ హబ్",
    phone: "9988776655",
    verified: true,
    available: false,
    year: 2022,
    specification: "Paddy • Operator included",
    responseTime: { te: "సాధారణంగా 45 నిమిషాల్లో స్పందిస్తారు", en: "Usually replies in 45 minutes" },
    description: {
      te: "ఆపరేటర్‌తో వచ్చే అధిక సామర్థ్యం గల వరి కోత యంత్రం. ముందస్తు బుకింగ్ అవసరం.",
      en: "A high-capacity paddy harvester with an operator. Advance booking is required.",
    },
  },
];

export const productCopy = {
  te: {
    languageButton: "English",
    v1: "V1 వెతకండి",
    v2: "V2 బుక్ చేయండి",
    login: "లాగిన్",
    headline: "మీ దగ్గరలోని వ్యవసాయ పరికరాలు",
    subheadline: "మండలం ఎంచుకుని వెంటనే యజమానిని సంప్రదించండి",
    district: "జిల్లా",
    mandal: "మండలం",
    village: "గ్రామం",
    search: "పరికరాలు వెతకండి",
    searchLabel: "పరికరం పేరు",
    searchPlaceholder: "ట్రాక్టర్, రోటావేటర్...",
    filters: "ఫిల్టర్",
    all: "అన్నీ",
    availableNow: "ఇప్పుడు అందుబాటులో ఉంది",
    busy: "ప్రస్తుతం బిజీగా ఉంది",
    details: "వివరాలు",
    hideDetails: "వివరాలు మూసివేయండి",
    call: "కాల్ చేయండి",
    whatsapp: "WhatsApp",
    verifiedOwner: "ధృవీకరించిన యజమాని",
    ownerDetails: "యజమాని వివరాలు",
    noResults: "ఈ ఎంపికలకు పరికరాలు దొరకలేదు.",
    reset: "ఫిల్టర్లు తీసివేయండి",
    saved: "సేవ్ అయింది",
    save: "సేవ్ చేయండి",
    results: "దగ్గరలోని పరికరాలు",
    home: "హోమ్",
    discover: "వెతకండి",
    favorites: "సేవ్ చేసినవి",
    profile: "ప్రొఫైల్",
    bookingTitle: "బుకింగ్ వివరాలు",
    chat: "చాట్ చేయండి",
    startBooking: "బుకింగ్ ప్రారంభించండి",
    date: "తేదీ",
    time: "సమయం",
    duration: "ఎన్ని రోజులు",
    oneDay: "1 రోజు",
    twoDays: "2 రోజులు",
    threeDays: "3 రోజులు",
    rent: "అద్దె",
    serviceFee: "సేవా రుసుము",
    total: "మొత్తం",
    pay: "చెల్లించండి",
    trust: "యజమాని అంగీకరించిన తర్వాత మాత్రమే బుకింగ్ ఖాయం అవుతుంది",
    request: "అభ్యర్థన",
    ownerAccept: "యజమాని అంగీకారం",
    payment: "చెల్లింపు",
    complete: "పూర్తి",
    messagePlaceholder: "మీ సందేశం టైప్ చేయండి...",
    farmerMessage: "రేపు ఉదయం ట్రాక్టర్ అందుబాటులో ఉందా?",
    ownerMessage: "అవును, 7 గంటలకు పంపగలను.",
    send: "పంపండి",
    newBooking: "యజమానికి కొత్త బుకింగ్ అభ్యర్థన",
    accept: "అంగీకరించండి",
    reject: "తిరస్కరించండి",
    ownerReceives: "యజమానికి వచ్చే మొత్తం",
    bookingSent: "బుకింగ్ అభ్యర్థన పంపబడింది",
    paymentReady: "చెల్లింపు విజయవంతమైంది — యజమాని అంగీకారం కోసం వేచి ఉంది",
  },
  en: {
    languageButton: "తెలుగు",
    v1: "V1 Discover",
    v2: "V2 Book",
    login: "Sign in",
    headline: "Farm equipment near you",
    subheadline: "Choose your mandal and contact the owner right away",
    district: "District",
    mandal: "Mandal",
    village: "Village",
    search: "Search equipment",
    searchLabel: "Equipment name",
    searchPlaceholder: "Tractor, rotavator...",
    filters: "Filters",
    all: "All",
    availableNow: "Available now",
    busy: "Currently busy",
    details: "Details",
    hideDetails: "Hide details",
    call: "Call owner",
    whatsapp: "WhatsApp",
    verifiedOwner: "Verified owner",
    ownerDetails: "Owner details",
    noResults: "No equipment matches these selections.",
    reset: "Clear filters",
    saved: "Saved",
    save: "Save",
    results: "Equipment nearby",
    home: "Home",
    discover: "Search",
    favorites: "Saved",
    profile: "Profile",
    bookingTitle: "Booking details",
    chat: "Chat",
    startBooking: "Start booking",
    date: "Date",
    time: "Time",
    duration: "Duration",
    oneDay: "1 day",
    twoDays: "2 days",
    threeDays: "3 days",
    rent: "Rental",
    serviceFee: "Service fee",
    total: "Total",
    pay: "Pay",
    trust: "The booking is confirmed only after the owner accepts it",
    request: "Request",
    ownerAccept: "Owner accepts",
    payment: "Payment",
    complete: "Complete",
    messagePlaceholder: "Type your message...",
    farmerMessage: "Is the tractor available tomorrow morning?",
    ownerMessage: "Yes, I can send it at 7 AM.",
    send: "Send",
    newBooking: "New booking request for the owner",
    accept: "Accept",
    reject: "Reject",
    ownerReceives: "Owner receives",
    bookingSent: "Booking request sent",
    paymentReady: "Payment successful — waiting for owner acceptance",
  },
} as const;
