"use client";

import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, WalletCards } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { AdminHeader, AdminSidebar, AdminSidebarBackdrop } from "../admin-chrome";

type Payment = { id: string; booking_request_id: string; owner_name: string; listing_title: string; owner_amount: number; status: string; payout_status: string; gateway_payment_id: string | null; booking: { rental_status?: string } | null };
const money = (value: unknown) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(Number(value ?? 0));
const pretty = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (character) => character.toUpperCase());

export default function AdminPayments({ adminName }: { adminName: string }) {
  const [payments, setPayments] = useState<Payment[]>([]); const [filter, setFilter] = useState("all"); const [open, setOpen] = useState(false); const [working, setWorking] = useState("");
  async function load() { const response = await fetch("/api/admin/payments", { cache: "no-store" }); const body = (await response.json().catch(() => ({}))) as { payments?: Payment[]; message?: string }; if (!response.ok) throw new Error(body.message ?? "Unable to load payments"); setPayments(body.payments ?? []); }
  useEffect(() => { const timer = window.setTimeout(() => { void load().catch((reason: unknown) => toast.error(reason instanceof Error ? reason.message : "Unable to load payments")); }, 0); return () => window.clearTimeout(timer); }, []);
  const visible = useMemo(() => filter === "all" ? payments : payments.filter((payment) => payment.payout_status === filter), [payments, filter]);
  async function markPaid(payment: Payment) { if (!window.confirm(`Mark Owner Payout as Paid?\n\nOwner: ${payment.owner_name}\nBooking: MR-${payment.booking_request_id.slice(0, 8).toUpperCase()}\nAmount: ${money(payment.owner_amount)}\n\nThis records the payout as completed.`)) return; setWorking(payment.id); try { const response = await fetch(`/api/admin/payouts/${payment.id}/mark-paid`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({}) }); const body = (await response.json().catch(() => ({}))) as { message?: string }; if (!response.ok) throw new Error(body.message ?? "Unable to record payout"); await load(); toast.success("Owner payout recorded as paid."); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to record payout"); } finally { setWorking(""); } }
  return <div className="admin-dashboard admin-subpage"><AdminSidebarBackdrop open={open} onClose={() => setOpen(false)} /><AdminSidebar active="payments" open={open} onClose={() => setOpen(false)} /><main className="admin-main"><AdminHeader title="Payments & payouts" subtitle="Review successful payments and record eligible owner payouts." adminName={adminName} onMenu={() => setOpen(true)} /><section className="admin-panel admin-subpage-panel"><div className="admin-panel-heading"><div><p className="admin-eyebrow">Owner payout ledger</p><h2><WalletCards size={20} />Payment records</h2></div></div><div className="admin-filter-row">{["all", "pending", "eligible", "paid", "failed", "not_applicable"].map((item) => <button type="button" key={item} className={filter === item ? "is-active" : undefined} onClick={() => setFilter(item)}>{item === "all" ? "All" : pretty(item)}</button>)}</div>{visible.length ? <div className="admin-table-scroll"><table className="admin-table"><thead><tr>{["Payment", "Owner", "Equipment", "Booking", "Payment status", "Owner amount", "Payout", "Action"].map((heading) => <th key={heading}>{heading}</th>)}</tr></thead><tbody>{visible.map((payment) => <tr key={payment.id}><td><strong>{payment.gateway_payment_id ?? "Pending gateway reference"}</strong><small>{payment.id.slice(0, 8).toUpperCase()}</small></td><td>{payment.owner_name}</td><td>{payment.listing_title}</td><td>MR-{payment.booking_request_id.slice(0, 8).toUpperCase()}</td><td>{pretty(payment.status)}</td><td className="nowrap">{money(payment.owner_amount)}</td><td><span className={`admin-status admin-status-${payment.payout_status === "paid" ? "success" : payment.payout_status === "eligible" ? "blue" : payment.payout_status === "failed" ? "danger" : "warning"}`}><i />{pretty(payment.payout_status)}</span></td><td>{payment.payout_status === "eligible" ? <Button size="sm" disabled={working === payment.id} onClick={() => void markPaid(payment)}><CheckCircle2 size={15} /> Mark as paid</Button> : payment.payout_status === "paid" ? "Recorded" : "—"}</td></tr>)}</tbody></table></div> : <div className="admin-empty"><WalletCards size={20} />No payment records match this filter.</div>}</section></main></div>;
}
