"""Build browser and Supabase location fixtures from the official LGD CSV.

The data.gov.in village export currently contains a duplicate CSV heading, so
this script reads columns by position and emits a clean, deterministic tree.
"""

from __future__ import annotations

import csv
import json
from collections import OrderedDict
from datetime import datetime
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CSV_PATH = ROOT / "data" / "andhra-pradesh-villages-lgd.csv"
JSON_PATH = ROOT / "data" / "andhra-pradesh-locations.json"
SQL_PATH = ROOT.parent / "supabase-be" / "supabase" / "seed_locations.sql"


def clean(value: str) -> str:
    return " ".join(value.strip().split())


def load_rows() -> list[dict[str, object]]:
    locations: list[dict[str, object]] = []
    seen: set[tuple[str, str, str, str]] = set()

    with CSV_PATH.open("r", encoding="utf-8-sig", newline="") as source:
        reader = csv.reader(source)
        next(reader)
        for row in reader:
            if len(row) < 17:
                continue
            village_code = clean(row[0])
            village = clean(row[1])
            mandal_code = clean(row[4])
            mandal = clean(row[5])
            district_code = clean(row[8])
            district = clean(row[9])
            if not all((village_code, village, mandal_code, mandal, district_code, district)):
                continue
            key = (district_code, mandal_code, village_code, village.casefold())
            if key in seen:
                continue
            seen.add(key)
            locations.append(
                {
                    "districtCode": district_code,
                    "district": district,
                    "mandalCode": mandal_code,
                    "mandal": mandal,
                    "villageCode": village_code,
                    "village": village,
                    "lastUpdated": clean(row[16]),
                }
            )

    # LGD can retain older rows after a sub-district rename. Resolve each LGD
    # code to the newest published name, while keeping every village record.
    latest_mandal_names: dict[str, tuple[datetime, str]] = {}
    for item in locations:
        raw_date = str(item["lastUpdated"])
        try:
            updated = datetime.strptime(raw_date, "%d-%m-%Y")
        except ValueError:
            updated = datetime.min
        code = str(item["mandalCode"])
        current = latest_mandal_names.get(code)
        if current is None or updated > current[0]:
            latest_mandal_names[code] = (updated, str(item["mandal"]))

    for item in locations:
        item["mandal"] = latest_mandal_names[str(item["mandalCode"])][1]
        item.pop("lastUpdated", None)
    return locations


def build_tree(rows: list[dict[str, object]]) -> dict[str, object]:
    district_map: OrderedDict[str, dict[str, object]] = OrderedDict()
    for row in sorted(
        rows,
        key=lambda item: (
            str(item["district"]).casefold(),
            str(item["mandal"]).casefold(),
            str(item["village"]).casefold(),
            str(item["villageCode"]),
        ),
    ):
        district_code = str(row["districtCode"])
        district = district_map.setdefault(
            district_code,
            {"code": district_code, "name": row["district"], "mandals": OrderedDict()},
        )
        mandals = district["mandals"]
        assert isinstance(mandals, OrderedDict)
        mandal_code = str(row["mandalCode"])
        mandal = mandals.setdefault(
            mandal_code,
            {"code": mandal_code, "name": row["mandal"], "villages": []},
        )
        villages = mandal["villages"]
        assert isinstance(villages, list)
        villages.append({"code": row["villageCode"], "name": row["village"]})

    districts: list[dict[str, object]] = []
    mandal_count = 0
    village_count = 0
    for district in district_map.values():
        mandal_values = list(district.pop("mandals").values())
        district["mandals"] = mandal_values
        mandal_count += len(mandal_values)
        village_count += sum(len(mandal["villages"]) for mandal in mandal_values)
        districts.append(district)

    return {
        "source": "Local Government Directory (LGD), Ministry of Panchayati Raj via data.gov.in",
        "sourceUrl": "https://www.data.gov.in/resource/local-government-directory-lgd-villages",
        "catalogUpdatedOn": "2026-07-30",
        "generatedOn": "2026-08-16",
        "totals": {
            "districts": len(districts),
            "mandals": mandal_count,
            "villages": village_count,
        },
        "districts": districts,
    }


def build_sql(rows: list[dict[str, object]]) -> str:
    compact = json.dumps(rows, ensure_ascii=False, separators=(",", ":"))
    return f"""-- Generated by frontend/scripts/build_location_data.py.
-- Source: Local Government Directory (LGD), Ministry of Panchayati Raj.
-- Catalog updated 2026-07-30; generated 2026-08-16.

do $$
declare
  payload jsonb := $locations${compact}$locations$::jsonb;
begin
  insert into public.districts (name, lgd_code)
  select distinct item->>'district', (item->>'districtCode')::integer
  from jsonb_array_elements(payload) item
  on conflict (lgd_code) do update set name = excluded.name;

  insert into public.mandals (district_id, name, lgd_code)
  select distinct d.id, item->>'mandal', (item->>'mandalCode')::integer
  from jsonb_array_elements(payload) item
  join public.districts d on d.lgd_code = (item->>'districtCode')::integer
  on conflict (lgd_code) do update
  set district_id = excluded.district_id, name = excluded.name;

  insert into public.villages (mandal_id, name, lgd_code)
  select distinct m.id, item->>'village', (item->>'villageCode')::integer
  from jsonb_array_elements(payload) item
  join public.mandals m on m.lgd_code = (item->>'mandalCode')::integer
  on conflict (lgd_code) do update
  set mandal_id = excluded.mandal_id, name = excluded.name;
end;
$$;
"""


def main() -> None:
    rows = load_rows()
    tree = build_tree(rows)
    JSON_PATH.write_text(
        json.dumps(tree, ensure_ascii=False, separators=(",", ":")),
        encoding="utf-8",
    )
    SQL_PATH.write_text(build_sql(rows), encoding="utf-8")
    print(json.dumps(tree["totals"], indent=2))


if __name__ == "__main__":
    main()
