import { NextRequest, NextResponse } from "next/server";
import { getCurrentUser, getSupabaseAdmin } from "@/lib/server-auth";

const PAGE = 1000;
async function all<T>(supabase: ReturnType<typeof getSupabaseAdmin>, table: string, columns: string) { const result: T[] = []; for (let from = 0; ; from += PAGE) { const { data, error } = await supabase.from(table).select(columns).range(from, from + PAGE - 1); if (error) throw error; result.push(...((data ?? []) as T[])); if (!data || data.length < PAGE) return result; } }
const amount = (value: unknown) => Number(value ?? 0);
const startFor = (range: string) => { const date = new Date(); date.setHours(0, 0, 0, 0); if (range === "today") return date; if (range === "7d") date.setDate(date.getDate() - 6); else if (range === "30d") date.setDate(date.getDate() - 29); else if (range === "month") date.setDate(1); else return null; return date; };

export async function GET(request: NextRequest) {
  try {
    const currentUser = await getCurrentUser();
    if (!currentUser) return NextResponse.json({ error: "UNAUTHORIZED", message: "Authentication is required" }, { status: 401 });
    if (currentUser.profile.role !== "admin") return NextResponse.json({ error: "FORBIDDEN", message: "Admin access is required" }, { status: 403 });
    const range = request.nextUrl.searchParams.get("range") ?? "30d"; const start = startFor(range); const supabase = getSupabaseAdmin();
    type Profile = { id: string; full_name: string; role: string; is_verified: boolean; is_active: boolean; created_at: string };
    type Listing = { id: string; owner_id: string; category_id: string; district_id: string | null; status: string; title: string; created_at: string };
    type Booking = { id: string; owner_id: string; requester_id: string; listing_id: string; rental_status: string; total_amount: number; created_at: string };
    type Payment = { id: string; booking_request_id: string; owner_id: string; listing_id: string; status: string; gross_amount: number; platform_commission: number; owner_amount: number; payout_status: string; created_at: string; paid_at: string | null };
    const [profiles, listings, bookings, payments, categories, districts] = await Promise.all([
      all<Profile>(supabase, "profiles", "id, full_name, role, is_verified, is_active, created_at"), all<Listing>(supabase, "listings", "id, owner_id, category_id, district_id, status, title, created_at"), all<Booking>(supabase, "booking_requests", "id, owner_id, requester_id, listing_id, rental_status, total_amount, created_at"), all<Payment>(supabase, "payments", "id, booking_request_id, owner_id, listing_id, status, gross_amount, platform_commission, owner_amount, payout_status, created_at, paid_at"), all<{ id: string; name: string }>(supabase, "equipment_categories", "id, name"), all<{ id: string; name: string }>(supabase, "districts", "id, name"),
    ]);
    const inRange = (value: string) => !start || new Date(value) >= start;
    const periodProfiles = profiles.filter((row) => inRange(row.created_at)); const periodListings = listings.filter((row) => inRange(row.created_at)); const periodBookings = bookings.filter((row) => inRange(row.created_at)); const periodPayments = payments.filter((row) => inRange(row.paid_at ?? row.created_at));
    const successful = periodPayments.filter((row) => row.status === "paid" && periodBookings.find((booking) => booking.id === row.booking_request_id)?.rental_status !== "cancelled");
    const countBy = (rows: Array<{ [key: string]: unknown }>, key: string) => Object.entries(rows.reduce<Record<string, number>>((map, row) => { const value = String(row[key] ?? "unknown"); map[value] = (map[value] ?? 0) + 1; return map; }, {})).map(([name, value]) => ({ name, value })).sort((a, b) => b.value - a.value);
    const profileById = new Map(profiles.map((row) => [row.id, row])); const categoryById = new Map(categories.map((row) => [row.id, row.name])); const districtById = new Map(districts.map((row) => [row.id, row.name]));
    const topOwners = [...new Set(listings.map((row) => row.owner_id))].map((id) => { const ownerListings = periodListings.filter((row) => row.owner_id === id); const ownerBookings = periodBookings.filter((row) => row.owner_id === id && row.rental_status === "completed"); const ownerPayments = successful.filter((row) => row.owner_id === id); return { name: profileById.get(id)?.full_name ?? "Owner", listings: ownerListings.length, completedRentals: ownerBookings.length, grossRentalValue: ownerPayments.reduce((sum, row) => sum + amount(row.gross_amount), 0), ownerEarnings: ownerPayments.reduce((sum, row) => sum + amount(row.owner_amount), 0) }; }).sort((a, b) => b.grossRentalValue - a.grossRentalValue).slice(0, 10);
    const dayKeys = [...new Set([...periodProfiles.map((row) => row.created_at.slice(0, 10)), ...periodBookings.map((row) => row.created_at.slice(0, 10)), ...periodPayments.map((row) => (row.paid_at ?? row.created_at).slice(0, 10))])].sort();
    const trend = dayKeys.map((day) => ({ date: day, users: periodProfiles.filter((row) => row.created_at.slice(0, 10) === day).length, bookings: periodBookings.filter((row) => row.created_at.slice(0, 10) === day).length, revenue: successful.filter((row) => (row.paid_at ?? row.created_at).slice(0, 10) === day).reduce((sum, row) => sum + amount(row.gross_amount), 0) }));
    return NextResponse.json({ range, metrics: { totalUsers: profiles.length, farmers: profiles.filter((row) => row.role === "farmer").length, owners: profiles.filter((row) => row.role === "owner").length, admins: profiles.filter((row) => row.role === "admin").length, verifiedOwners: profiles.filter((row) => row.role === "owner" && row.is_verified).length, blockedUsers: profiles.filter((row) => row.is_active === false).length, totalListings: listings.length, liveListings: listings.filter((row) => row.status === "live").length, draftListings: listings.filter((row) => row.status === "draft").length, pausedListings: listings.filter((row) => row.status === "paused").length, archivedListings: listings.filter((row) => row.status === "archived").length, totalBookings: bookings.length, requestedBookings: bookings.filter((row) => row.rental_status === "requested").length, confirmedBookings: bookings.filter((row) => row.rental_status === "confirmed").length, inProgressBookings: bookings.filter((row) => row.rental_status === "in_progress").length, completedBookings: bookings.filter((row) => row.rental_status === "completed").length, cancelledBookings: bookings.filter((row) => row.rental_status === "cancelled").length, successfulPayments: successful.length, failedPayments: periodPayments.filter((row) => row.status === "failed").length, refundedPayments: periodPayments.filter((row) => row.status === "refunded").length, grossTransactionValue: successful.reduce((sum, row) => sum + amount(row.gross_amount), 0), platformCommission: successful.reduce((sum, row) => sum + amount(row.platform_commission), 0), ownerPayable: successful.filter((row) => row.payout_status !== "paid").reduce((sum, row) => sum + amount(row.owner_amount), 0), ownerPaid: successful.filter((row) => row.payout_status === "paid").reduce((sum, row) => sum + amount(row.owner_amount), 0), pendingPayouts: successful.filter((row) => ["pending", "eligible"].includes(row.payout_status)).reduce((sum, row) => sum + amount(row.owner_amount), 0) }, charts: { bookingsByStatus: countBy(periodBookings, "rental_status"), paymentsByStatus: countBy(periodPayments, "status"), listingsByCategory: periodListings.map((row) => ({ ...row, category: categoryById.get(row.category_id) ?? "Unknown" })).reduce<Record<string, number>>((map, row) => { map[row.category] = (map[row.category] ?? 0) + 1; return map; }, {}), topDistricts: periodListings.map((row) => districtById.get(row.district_id ?? "") ?? "Unknown").reduce<Record<string, number>>((map, name) => { map[name] = (map[name] ?? 0) + 1; return map; }, {}), trend }, topOwners });
  } catch (error) { console.error("Admin reports API error", error); return NextResponse.json({ error: "ADMIN_REPORTS_FAILED", message: "Unable to load reports" }, { status: 500 }); }
}
